FROM php:apache-bullseye

COPY config/000-default.conf /etc/apache2/sites-available/
COPY config/default-ssl.conf /etc/apache2/sites-available/
COPY config/gencert.sh /usr/local/bin/
COPY entrypoint /entrypoint
RUN chmod +x /usr/local/bin/gencert.sh


RUN	echo Get some packages ... && \
  apt-get update && \	
  apt-get -y install cron python3 python3-pip git gcc libffi-dev libssl-dev cargo sed netcat-traditional && \
  echo Enable Apache stuff ... && \
  a2enmod proxy rewrite proxy_http proxy_wstunnel	ssl socache_shmcb headers && \
  a2dissite default-ssl.conf && \
  echo Get the Dashboard ... && \
	cd /opt && \
	git clone https://github.com/sgtsmall/FDMR-Monitor.git && \
  echo Install required stuff... && \
	cd FDMR-Monitor && \
	pip install --no-cache-dir -r requirements.txt && \
  echo Cleaning stuff... && \
  apt-get purge -y git gcc libffi-dev libssl-dev cargo && \
  apt-get autoremove -y && \
  echo Adding Cron stuff... && \
  mkdir -p /var/spool/crontabs && \
	echo "50 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null" > /var/spool/crontabs/root && \
  echo DONE
  
RUN chmod +x /entrypoint


ENTRYPOINT [ "/entrypoint" ]
